config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"

  get "/menus/changemenu" => "menus#changeMenu", as: :change_menus
  put "/menus/:id/updateMenuName" => "menus#updateMenuName"
  put "menu_items/:id/updateMenuItem" => "menu_items#updateMenuItem"

  get "/signin/new" => "sessions#new", as: :new_session
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy"

  post "/users/:id/removeAsClerk" => "users#removeAsClerk"
  post "/users/:id/makeAsClerk" => "users#makeAsClerk"

  get "/reports/:id" => "reports#invoice", as: :invoice

  post "/orderdeliver/:id" => "orders#deliverOrder"
  post "/orders/confirm" => "orders#confirm"
  get "/orders/cart" => "orders#cart", as: :carts

  put "/order_items/:id/decrement" => "order_items#decrement"
  put "/order_items/:id/decrementInCart" => "order_items#decrementInCart"

  post "/order_items/:id/addToCart" => "order_items#addToCart"

  put "/order_items/:id/increment" => "order_items#increment"
  put "/order_items/:id/incrementInCart" => "order_items#incrementInCart"

  get "/TermsAndConditionsDisplay" => "others#termsAndConditionsDisplay"
  get "/TermsAndConditionsShow" => "others#termsAndConditionsShow"
  post "/TermsAndConditionsUpdate" => "others#termsAndConditionsUpdate"

  get "/SocialMediaHandlesShow" => "others#socialMediaHandlesShow"
  post "/SocialMediaHandlesUpdate" => "others#socialMediaHandlesUpdate"

  get "/CafeAddressShow" => "others#cafeAddressShow"
  post "/CafeAddressUpdate" => "others#cafeAddressUpdate"

  resources :menus
  resources :menu_items
  resources :order_items
  resources :users
  resources :applicants
  resources :categories
  resources :questions
  resources :answers
  resources :reports
  resources :orders
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :delete_all
  validates :query, presence: true, length: {minimum: 10}
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_owner_or_clerk_logged_in, only: [:show]

  def index
    role = "customer"
    role = current_user.role if current_user
    render "index", locals: { role: role }
  end

  def create
    name = "Anonymous"
    name = current_user.name if current_user

    query = params[:query]
    question = Question.new(name: name, query: query)

    if question.valid?
      question.save
      flash[:notice] = "Question added successfully"
    else
      flash[:error] = question.errors.full_messages.join(", ")
    end

    redirect_to questions_path
  end

  def show
    id = params[:id]
    question = Question.find(id)
    render "show", locals: { question: question }
  end
end

app/views/questions/_add-query.html.erb
<div class="add-new-query">
  <p class="add-new-query-text"> Want to ask us something !!! </p>
  <%= form_with(url: questions_path, method: "post", class: "add-new-query-form") do %>
    <%= text_area_tag(:query, nil, placeholder: "Drop your question here", class: "add-new-solution-queryText") %>
    <%= submit_tag("Post !", class: "add-new-query-form-submit", data: {disable_with: "Posting.."}) %>
  <% end %>
</div>

app/views/questions/_answers-block.html.erb
<% question.answers.each do |answer| %>
  <div class="answer">
    <p> <%= answer.solution %> </p>
  </div>
<% end %>

app/views/questions/_queries-solutions.html.erb
<div class="questions">
  <% Question.order(id: :desc).each do |question| %>
    <div class="question">
      <%= render partial: "query-block", locals: { question: question, role: role } %>
      <div class="answers">
        <%= render partial: "answers-block", locals: { question: question } %>
      </div>
    </div>
    <hr class="questions-hr">
  <% end %>
</div>

app/views/questions/_query-block.html.erb
<div class="query-block">
  <p class="query-text"> <%= question.query %> </p>
  <div class="question-flex">
    <p> Asked by <span class="asked-by"> <%= question.name %> </span> </p>
    <% if role && role != "customer" %>
      <p> <%= link_to ('<i class="fa fa-reply add-an-answer"> Add an answer </i>').html_safe, "/questions/#{question.id}" %> </p>
    <% elsif question.answers.count == 0 %>
      <p class="no-answer-text"> Yet to be answered </p>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<% if role == "customer" %>
  <%= render partial: "add-query" %>
<% end %>
<h1 class="FAQ-title"> FAQ </h1>
<%= render partial: "queries-solutions", locals: { role: role } %>

app/views/questions/show.html.erb
<div class="questions">
  <div class="question">
    <%= render partial: "query-block", locals: { question: question, role: nil } %>
    <div class="answers">
      <%= form_with(url: answers_path, method: "post", class: "add-new-solution") do %>
        <%= hidden_field_tag(:question_id, question.id) %>
        <%= text_area_tag(:solution, nil, placeholder: "Answer here", class: "add-new-solution-queryText") %>
        <%= submit_tag("Post !", class: "add-new-query-form-submit", data: {disable_with: "Posting.."}) %>
      <% end %>
      <%= render partial: "answers-block", locals: { question: question } %>
    </div>
  </div>
</div>